export const data = [
  { code: "AF", code3: "AFG", name: "Afghanistan", number: "004" },
  { code: "AL", code3: "ALB", name: "Albania", number: "008" },
  { code: "DZ", code3: "DZA", name: "Algeria", number: "012" },
  { code: "AS", code3: "ASM", name: "American Samoa", number: "016" },
  { code: "AD", code3: "AND", name: "Andorra", number: "020" },
  { code: "AO", code3: "AGO", name: "Angola", number: "024" },
  { code: "AI", code3: "AIA", name: "Anguilla", number: "660" },
  { code: "AQ", code3: "ATA", name: "Antarctica", number: "010" },
  { code: "AG", code3: "ATG", name: "Antigua and Barbuda", number: "028" },
  { code: "AR", code3: "ARG", name: "Argentina", number: "032" },
  { code: "AM", code3: "ARM", name: "Armenia", number: "051" },
  { code: "AW", code3: "ABW", name: "Aruba", number: "533" },
  { code: "AU", code3: "AUS", name: "Australia", number: "036" },
  { code: "AT", code3: "AUT", name: "Austria", number: "040" },
  { code: "AZ", code3: "AZE", name: "Azerbaijan", number: "031" },
  { code: "BS", code3: "BHS", name: "Bahamas (the)", number: "044" },
  { code: "BH", code3: "BHR", name: "Bahrain", number: "048" },
  { code: "BD", code3: "BGD", name: "Bangladesh", number: "050" },
  { code: "BB", code3: "BRB", name: "Barbados", number: "052" },
  { code: "BY", code3: "BLR", name: "Belarus", number: "112" },
  { code: "BE", code3: "BEL", name: "Belgium", number: "056" },
  { code: "BZ", code3: "BLZ", name: "Belize", number: "084" },
  { code: "BJ", code3: "BEN", name: "Benin", number: "204" },
  { code: "BM", code3: "BMU", name: "Bermuda", number: "060" },
  { code: "BT", code3: "BTN", name: "Bhutan", number: "064" },
  {
    code: "BO",
    code3: "BOL",
    name: "Bolivia (Plurinational State of)",
    number: "068",
  },
  {
    code: "BQ",
    code3: "BES",
    name: "Bonaire, Sint Eustatius and Saba",
    number: "535",
  },
  { code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", number: "070" },
  { code: "BW", code3: "BWA", name: "Botswana", number: "072" },
  { code: "BV", code3: "BVT", name: "Bouvet Island", number: "074" },
  { code: "BR", code3: "BRA", name: "Brazil", number: "076" },
  {
    code: "IO",
    code3: "IOT",
    name: "British Indian Ocean Territory (the)",
    number: "086",
  },
  { code: "BN", code3: "BRN", name: "Brunei Darussalam", number: "096" },
  { code: "BG", code3: "BGR", name: "Bulgaria", number: "100" },
  { code: "BF", code3: "BFA", name: "Burkina Faso", number: "854" },
  { code: "BI", code3: "BDI", name: "Burundi", number: "108" },
  { code: "CV", code3: "CPV", name: "Cabo Verde", number: "132" },
  { code: "KH", code3: "KHM", name: "Cambodia", number: "116" },
  { code: "CM", code3: "CMR", name: "Cameroon", number: "120" },
  { code: "CA", code3: "CAN", name: "Canada", number: "124" },
  { code: "KY", code3: "CYM", name: "Cayman Islands (the)", number: "136" },
  {
    code: "CF",
    code3: "CAF",
    name: "Central African Republic (the)",
    number: "140",
  },
  { code: "TD", code3: "TCD", name: "Chad", number: "148" },
  { code: "CL", code3: "CHL", name: "Chile", number: "152" },
  { code: "CN", code3: "CHN", name: "China", number: "156" },
  { code: "CX", code3: "CXR", name: "Christmas Island", number: "162" },
  {
    code: "CC",
    code3: "CCK",
    name: "Cocos (Keeling) Islands (the)",
    number: "166",
  },
  { code: "CO", code3: "COL", name: "Colombia", number: "170" },
  { code: "KM", code3: "COM", name: "Comoros (the)", number: "174" },
  {
    code: "CD",
    code3: "COD",
    name: "Congo (the Democratic Republic of the)",
    number: "180",
  },
  { code: "CG", code3: "COG", name: "Congo (the)", number: "178" },
  { code: "CK", code3: "COK", name: "Cook Islands (the)", number: "184" },
  { code: "CR", code3: "CRI", name: "Costa Rica", number: "188" },
  { code: "HR", code3: "HRV", name: "Croatia", number: "191" },
  { code: "CU", code3: "CUB", name: "Cuba", number: "192" },
  { code: "CW", code3: "CUW", name: "Curaçao", number: "531" },
  { code: "CY", code3: "CYP", name: "Cyprus", number: "196" },
  { code: "CZ", code3: "CZE", name: "Czechia", number: "203" },
  { code: "CI", code3: "CIV", name: "Côte d'Ivoire", number: "384" },
  { code: "DK", code3: "DNK", name: "Denmark", number: "208" },
  { code: "DJ", code3: "DJI", name: "Djibouti", number: "262" },
  { code: "DM", code3: "DMA", name: "Dominica", number: "212" },
  { code: "DO", code3: "DOM", name: "Dominican Republic (the)", number: "214" },
  { code: "EC", code3: "ECU", name: "Ecuador", number: "218" },
  { code: "EG", code3: "EGY", name: "Egypt", number: "818" },
  { code: "SV", code3: "SLV", name: "El Salvador", number: "222" },
  { code: "GQ", code3: "GNQ", name: "Equatorial Guinea", number: "226" },
  { code: "ER", code3: "ERI", name: "Eritrea", number: "232" },
  { code: "EE", code3: "EST", name: "Estonia", number: "233" },
  { code: "SZ", code3: "SWZ", name: "Eswatini", number: "748" },
  { code: "ET", code3: "ETH", name: "Ethiopia", number: "231" },
  {
    code: "FK",
    code3: "FLK",
    name: "Falkland Islands (the) [Malvinas]",
    number: "238",
  },
  { code: "FO", code3: "FRO", name: "Faroe Islands (the)", number: "234" },
  { code: "FJ", code3: "FJI", name: "Fiji", number: "242" },
  { code: "FI", code3: "FIN", name: "Finland", number: "246" },
  { code: "FR", code3: "FRA", name: "France", number: "250" },
  { code: "GF", code3: "GUF", name: "French Guiana", number: "254" },
  { code: "PF", code3: "PYF", name: "French Polynesia", number: "258" },
  {
    code: "TF",
    code3: "ATF",
    name: "French Southern Territories (the)",
    number: "260",
  },
  { code: "GA", code3: "GAB", name: "Gabon", number: "266" },
  { code: "GM", code3: "GMB", name: "Gambia (the)", number: "270" },
  { code: "GE", code3: "GEO", name: "Georgia", number: "268" },
  { code: "DE", code3: "DEU", name: "Germany", number: "276" },
  { code: "GH", code3: "GHA", name: "Ghana", number: "288" },
  { code: "GI", code3: "GIB", name: "Gibraltar", number: "292" },
  { code: "GR", code3: "GRC", name: "Greece", number: "300" },
  { code: "GL", code3: "GRL", name: "Greenland", number: "304" },
  { code: "GD", code3: "GRD", name: "Grenada", number: "308" },
  { code: "GP", code3: "GLP", name: "Guadeloupe", number: "312" },
  { code: "GU", code3: "GUM", name: "Guam", number: "316" },
  { code: "GT", code3: "GTM", name: "Guatemala", number: "320" },
  { code: "GG", code3: "GGY", name: "Guernsey", number: "831" },
  { code: "GN", code3: "GIN", name: "Guinea", number: "324" },
  { code: "GW", code3: "GNB", name: "Guinea-Bissau", number: "624" },
  { code: "GY", code3: "GUY", name: "Guyana", number: "328" },
  { code: "HT", code3: "HTI", name: "Haiti", number: "332" },
  {
    code: "HM",
    code3: "HMD",
    name: "Heard Island and McDonald Islands",
    number: "334",
  },
  { code: "VA", code3: "VAT", name: "Holy See (the)", number: "336" },
  { code: "HN", code3: "HND", name: "Honduras", number: "340" },
  { code: "HK", code3: "HKG", name: "Hong Kong", number: "344" },
  { code: "HU", code3: "HUN", name: "Hungary", number: "348" },
  { code: "IS", code3: "ISL", name: "Iceland", number: "352" },
  { code: "IN", code3: "IND", name: "India", number: "356" },
  { code: "ID", code3: "IDN", name: "Indonesia", number: "360" },
  {
    code: "IR",
    code3: "IRN",
    name: "Iran (Islamic Republic of)",
    number: "364",
  },
  { code: "IQ", code3: "IRQ", name: "Iraq", number: "368" },
  { code: "IE", code3: "IRL", name: "Ireland", number: "372" },
  { code: "IM", code3: "IMN", name: "Isle of Man", number: "833" },
  { code: "IL", code3: "ISR", name: "Israel", number: "376" },
  { code: "IT", code3: "ITA", name: "Italy", number: "380" },
  { code: "JM", code3: "JAM", name: "Jamaica", number: "388" },
  { code: "JP", code3: "JPN", name: "Japan", number: "392" },
  { code: "JE", code3: "JEY", name: "Jersey", number: "832" },
  { code: "JO", code3: "JOR", name: "Jordan", number: "400" },
  { code: "KZ", code3: "KAZ", name: "Kazakhstan", number: "398" },
  { code: "KE", code3: "KEN", name: "Kenya", number: "404" },
  { code: "KI", code3: "KIR", name: "Kiribati", number: "296" },
  {
    code: "KP",
    code3: "PRK",
    name: "Korea (the Democratic People's Republic of)",
    number: "408",
  },
  { code: "KR", code3: "KOR", name: "Korea (the Republic of)", number: "410" },
  { code: "KW", code3: "KWT", name: "Kuwait", number: "414" },
  { code: "KG", code3: "KGZ", name: "Kyrgyzstan", number: "417" },
  {
    code: "LA",
    code3: "LAO",
    name: "Lao People's Democratic Republic (the)",
    number: "418",
  },
  { code: "LV", code3: "LVA", name: "Latvia", number: "428" },
  { code: "LB", code3: "LBN", name: "Lebanon", number: "422" },
  { code: "LS", code3: "LSO", name: "Lesotho", number: "426" },
  { code: "LR", code3: "LBR", name: "Liberia", number: "430" },
  { code: "LY", code3: "LBY", name: "Libya", number: "434" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", number: "438" },
  { code: "LT", code3: "LTU", name: "Lithuania", number: "440" },
  { code: "LU", code3: "LUX", name: "Luxembourg", number: "442" },
  { code: "MO", code3: "MAC", name: "Macao", number: "446" },
  { code: "MG", code3: "MDG", name: "Madagascar", number: "450" },
  { code: "MW", code3: "MWI", name: "Malawi", number: "454" },
  { code: "MY", code3: "MYS", name: "Malaysia", number: "458" },
  { code: "MV", code3: "MDV", name: "Maldives", number: "462" },
  { code: "ML", code3: "MLI", name: "Mali", number: "466" },
  { code: "MT", code3: "MLT", name: "Malta", number: "470" },
  { code: "MH", code3: "MHL", name: "Marshall Islands (the)", number: "584" },
  { code: "MQ", code3: "MTQ", name: "Martinique", number: "474" },
  { code: "MR", code3: "MRT", name: "Mauritania", number: "478" },
  { code: "MU", code3: "MUS", name: "Mauritius", number: "480" },
  { code: "YT", code3: "MYT", name: "Mayotte", number: "175" },
  { code: "MX", code3: "MEX", name: "Mexico", number: "484" },
  {
    code: "FM",
    code3: "FSM",
    name: "Micronesia (Federated States of)",
    number: "583",
  },
  {
    code: "MD",
    code3: "MDA",
    name: "Moldova (the Republic of)",
    number: "498",
  },
  { code: "MC", code3: "MCO", name: "Monaco", number: "492" },
  { code: "MN", code3: "MNG", name: "Mongolia", number: "496" },
  { code: "ME", code3: "MNE", name: "Montenegro", number: "499" },
  { code: "MS", code3: "MSR", name: "Montserrat", number: "500" },
  { code: "MA", code3: "MAR", name: "Morocco", number: "504" },
  { code: "MZ", code3: "MOZ", name: "Mozambique", number: "508" },
  { code: "MM", code3: "MMR", name: "Myanmar", number: "104" },
  { code: "NA", code3: "NAM", name: "Namibia", number: "516" },
  { code: "NR", code3: "NRU", name: "Nauru", number: "520" },
  { code: "NP", code3: "NPL", name: "Nepal", number: "524" },
  { code: "NL", code3: "NLD", name: "Netherlands (the)", number: "528" },
  { code: "NC", code3: "NCL", name: "New Caledonia", number: "540" },
  { code: "NZ", code3: "NZL", name: "New Zealand", number: "554" },
  { code: "NI", code3: "NIC", name: "Nicaragua", number: "558" },
  { code: "NE", code3: "NER", name: "Niger (the)", number: "562" },
  { code: "NG", code3: "NGA", name: "Nigeria", number: "566" },
  { code: "NU", code3: "NIU", name: "Niue", number: "570" },
  { code: "NF", code3: "NFK", name: "Norfolk Island", number: "574" },
  {
    code: "MP",
    code3: "MNP",
    name: "Northern Mariana Islands (the)",
    number: "580",
  },
  { code: "NO", code3: "NOR", name: "Norway", number: "578" },
  { code: "OM", code3: "OMN", name: "Oman", number: "512" },
  { code: "PK", code3: "PAK", name: "Pakistan", number: "586" },
  { code: "PW", code3: "PLW", name: "Palau", number: "585" },
  { code: "PS", code3: "PSE", name: "Palestine, State of", number: "275" },
  { code: "PA", code3: "PAN", name: "Panama", number: "591" },
  { code: "PG", code3: "PNG", name: "Papua New Guinea", number: "598" },
  { code: "PY", code3: "PRY", name: "Paraguay", number: "600" },
  { code: "PE", code3: "PER", name: "Peru", number: "604" },
  { code: "PH", code3: "PHL", name: "Philippines (the)", number: "608" },
  { code: "PN", code3: "PCN", name: "Pitcairn", number: "612" },
  { code: "PL", code3: "POL", name: "Poland", number: "616" },
  { code: "PT", code3: "PRT", name: "Portugal", number: "620" },
  { code: "PR", code3: "PRI", name: "Puerto Rico", number: "630" },
  { code: "QA", code3: "QAT", name: "Qatar", number: "634" },
  {
    code: "MK",
    code3: "MKD",
    name: "Republic of North Macedonia",
    number: "807",
  },
  { code: "RO", code3: "ROU", name: "Romania", number: "642" },
  { code: "RU", code3: "RUS", name: "Russian Federation (the)", number: "643" },
  { code: "RW", code3: "RWA", name: "Rwanda", number: "646" },
  { code: "RE", code3: "REU", name: "Réunion", number: "638" },
  { code: "BL", code3: "BLM", name: "Saint Barthélemy", number: "652" },
  {
    code: "SH",
    code3: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    number: "654",
  },
  { code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", number: "659" },
  { code: "LC", code3: "LCA", name: "Saint Lucia", number: "662" },
  {
    code: "MF",
    code3: "MAF",
    name: "Saint Martin (French part)",
    number: "663",
  },
  {
    code: "PM",
    code3: "SPM",
    name: "Saint Pierre and Miquelon",
    number: "666",
  },
  {
    code: "VC",
    code3: "VCT",
    name: "Saint Vincent and the Grenadines",
    number: "670",
  },
  { code: "WS", code3: "WSM", name: "Samoa", number: "882" },
  { code: "SM", code3: "SMR", name: "San Marino", number: "674" },
  { code: "ST", code3: "STP", name: "Sao Tome and Principe", number: "678" },
  { code: "SA", code3: "SAU", name: "Saudi Arabia", number: "682" },
  { code: "SN", code3: "SEN", name: "Senegal", number: "686" },
  { code: "RS", code3: "SRB", name: "Serbia", number: "688" },
  { code: "SC", code3: "SYC", name: "Seychelles", number: "690" },
  { code: "SL", code3: "SLE", name: "Sierra Leone", number: "694" },
  { code: "SG", code3: "SGP", name: "Singapore", number: "702" },
  {
    code: "SX",
    code3: "SXM",
    name: "Sint Maarten (Dutch part)",
    number: "534",
  },
  { code: "SK", code3: "SVK", name: "Slovakia", number: "703" },
  { code: "SI", code3: "SVN", name: "Slovenia", number: "705" },
  { code: "SB", code3: "SLB", name: "Solomon Islands", number: "090" },
  { code: "SO", code3: "SOM", name: "Somalia", number: "706" },
  { code: "ZA", code3: "ZAF", name: "South Africa", number: "710" },
  {
    code: "GS",
    code3: "SGS",
    name: "South Georgia and the South Sandwich Islands",
    number: "239",
  },
  { code: "SS", code3: "SSD", name: "South Sudan", number: "728" },
  { code: "ES", code3: "ESP", name: "Spain", number: "724" },
  { code: "LK", code3: "LKA", name: "Sri Lanka", number: "144" },
  { code: "SD", code3: "SDN", name: "Sudan (the)", number: "729" },
  { code: "SR", code3: "SUR", name: "Suriname", number: "740" },
  { code: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", number: "744" },
  { code: "SE", code3: "SWE", name: "Sweden", number: "752" },
  { code: "CH", code3: "CHE", name: "Switzerland", number: "756" },
  { code: "SY", code3: "SYR", name: "Syrian Arab Republic", number: "760" },
  { code: "TW", code3: "TWN", name: "Taiwan", number: "158" },
  { code: "TJ", code3: "TJK", name: "Tajikistan", number: "762" },
  {
    code: "TZ",
    code3: "TZA",
    name: "Tanzania, United Republic of",
    number: "834",
  },
  { code: "TH", code3: "THA", name: "Thailand", number: "764" },
  { code: "TL", code3: "TLS", name: "Timor-Leste", number: "626" },
  { code: "TG", code3: "TGO", name: "Togo", number: "768" },
  { code: "TK", code3: "TKL", name: "Tokelau", number: "772" },
  { code: "TO", code3: "TON", name: "Tonga", number: "776" },
  { code: "TT", code3: "TTO", name: "Trinidad and Tobago", number: "780" },
  { code: "TN", code3: "TUN", name: "Tunisia", number: "788" },
  { code: "TR", code3: "TUR", name: "Turkey", number: "792" },
  { code: "TM", code3: "TKM", name: "Turkmenistan", number: "795" },
  {
    code: "TC",
    code3: "TCA",
    name: "Turks and Caicos Islands (the)",
    number: "796",
  },
  { code: "TV", code3: "TUV", name: "Tuvalu", number: "798" },
  { code: "UG", code3: "UGA", name: "Uganda", number: "800" },
  { code: "UA", code3: "UKR", name: "Ukraine", number: "804" },
  {
    code: "AE",
    code3: "ARE",
    name: "United Arab Emirates (the)",
    number: "784",
  },
  {
    code: "GB",
    code3: "GBR",
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    number: "826",
  },
  {
    code: "UM",
    code3: "UMI",
    name: "United States Minor Outlying Islands (the)",
    number: "581",
  },
  {
    code: "US",
    code3: "USA",
    name: "United States of America (the)",
    number: "840",
  },
  { code: "UY", code3: "URY", name: "Uruguay", number: "858" },
  { code: "UZ", code3: "UZB", name: "Uzbekistan", number: "860" },
  { code: "VU", code3: "VUT", name: "Vanuatu", number: "548" },
  {
    code: "VE",
    code3: "VEN",
    name: "Venezuela (Bolivarian Republic of)",
    number: "862",
  },
  { code: "VN", code3: "VNM", name: "Viet Nam", number: "704" },
  { code: "VG", code3: "VGB", name: "Virgin Islands (British)", number: "092" },
  { code: "VI", code3: "VIR", name: "Virgin Islands (U.S.)", number: "850" },
  { code: "WF", code3: "WLF", name: "Wallis and Futuna", number: "876" },
  { code: "EH", code3: "ESH", name: "Western Sahara", number: "732" },
  { code: "YE", code3: "YEM", name: "Yemen", number: "887" },
  { code: "ZM", code3: "ZMB", name: "Zambia", number: "894" },
  { code: "ZW", code3: "ZWE", name: "Zimbabwe", number: "716" },
  { code: "AX", code3: "ALA", name: "Åland Islands", number: "248" },
];

export const cur = [
  {
    code: "AED",
    number: "784",
    digits: 2,
    currency: "UAE Dirham",
    countries: ["United Arab Emirates (The)"],
  },
  {
    code: "AFN",
    number: "971",
    digits: 2,
    currency: "Afghani",
    countries: ["Afghanistan"],
  },
  {
    code: "ALL",
    number: "008",
    digits: 2,
    currency: "Lek",
    countries: ["Albania"],
  },
  {
    code: "AMD",
    number: "051",
    digits: 2,
    currency: "Armenian Dram",
    countries: ["Armenia"],
  },
  {
    code: "ANG",
    number: "532",
    digits: 2,
    currency: "Netherlands Antillean Guilder",
    countries: ["Curaçao", "Sint Maarten (Dutch Part)"],
  },
  {
    code: "AOA",
    number: "973",
    digits: 2,
    currency: "Kwanza",
    countries: ["Angola"],
  },
  {
    code: "ARS",
    number: "032",
    digits: 2,
    currency: "Argentine Peso",
    countries: ["Argentina"],
  },
  {
    code: "AUD",
    number: "036",
    digits: 2,
    currency: "Australian Dollar",
    countries: [
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands (The)",
      "Heard Island and Mcdonald Islands",
      "Kiribati",
      "Nauru",
      "Norfolk Island",
      "Tuvalu",
    ],
  },
  {
    code: "AWG",
    number: "533",
    digits: 2,
    currency: "Aruban Florin",
    countries: ["Aruba"],
  },
  {
    code: "AZN",
    number: "944",
    digits: 2,
    currency: "Azerbaijan Manat",
    countries: ["Azerbaijan"],
  },
  {
    code: "BAM",
    number: "977",
    digits: 2,
    currency: "Convertible Mark",
    countries: ["Bosnia and Herzegovina"],
  },
  {
    code: "BBD",
    number: "052",
    digits: 2,
    currency: "Barbados Dollar",
    countries: ["Barbados"],
  },
  {
    code: "BDT",
    number: "050",
    digits: 2,
    currency: "Taka",
    countries: ["Bangladesh"],
  },
  {
    code: "BGN",
    number: "975",
    digits: 2,
    currency: "Bulgarian Lev",
    countries: ["Bulgaria"],
  },
  {
    code: "BHD",
    number: "048",
    digits: 3,
    currency: "Bahraini Dinar",
    countries: ["Bahrain"],
  },
  {
    code: "BIF",
    number: "108",
    digits: 0,
    currency: "Burundi Franc",
    countries: ["Burundi"],
  },
  {
    code: "BMD",
    number: "060",
    digits: 2,
    currency: "Bermudian Dollar",
    countries: ["Bermuda"],
  },
  {
    code: "BND",
    number: "096",
    digits: 2,
    currency: "Brunei Dollar",
    countries: ["Brunei Darussalam"],
  },
  {
    code: "BOB",
    number: "068",
    digits: 2,
    currency: "Boliviano",
    countries: ["Bolivia (Plurinational State Of)"],
  },
  {
    code: "BOV",
    number: "984",
    digits: 2,
    currency: "Mvdol",
    countries: ["Bolivia (Plurinational State Of)"],
  },
  {
    code: "BRL",
    number: "986",
    digits: 2,
    currency: "Brazilian Real",
    countries: ["Brazil"],
  },
  {
    code: "BSD",
    number: "044",
    digits: 2,
    currency: "Bahamian Dollar",
    countries: ["Bahamas (The)"],
  },
  {
    code: "BTN",
    number: "064",
    digits: 2,
    currency: "Ngultrum",
    countries: ["Bhutan"],
  },
  {
    code: "BWP",
    number: "072",
    digits: 2,
    currency: "Pula",
    countries: ["Botswana"],
  },
  {
    code: "BYR",
    number: "933",
    digits: 2,
    currency: "Belarusian Ruble",
    countries: ["Belarus"],
  },
  {
    code: "BYN",
    number: "933",
    digits: 2,
    currency: "Belarusian Ruble",
    countries: ["Belarus"],
  },
  {
    code: "BZD",
    number: "084",
    digits: 2,
    currency: "Belize Dollar",
    countries: ["Belize"],
  },
  {
    code: "CAD",
    number: "124",
    digits: 2,
    currency: "Canadian Dollar",
    countries: ["Canada"],
  },
  {
    code: "CDF",
    number: "976",
    digits: 2,
    currency: "Congolese Franc",
    countries: ["Congo (The Democratic Republic of The)"],
  },
  {
    code: "CHE",
    number: "947",
    digits: 2,
    currency: "WIR Euro",
    countries: ["Switzerland"],
  },
  {
    code: "CHF",
    number: "756",
    digits: 2,
    currency: "Swiss Franc",
    countries: ["Liechtenstein", "Switzerland"],
  },
  {
    code: "CHW",
    number: "948",
    digits: 2,
    currency: "WIR Franc",
    countries: ["Switzerland"],
  },
  {
    code: "CLF",
    number: "990",
    digits: 4,
    currency: "Unidad de Fomento",
    countries: ["Chile"],
  },
  {
    code: "CLP",
    number: "152",
    digits: 0,
    currency: "Chilean Peso",
    countries: ["Chile"],
  },
  {
    code: "CNY",
    number: "156",
    digits: 2,
    currency: "Yuan Renminbi",
    countries: ["China"],
  },
  {
    code: "COP",
    number: "170",
    digits: 2,
    currency: "Colombian Peso",
    countries: ["Colombia"],
  },
  {
    code: "COU",
    number: "970",
    digits: 2,
    currency: "Unidad de Valor Real",
    countries: ["Colombia"],
  },
  {
    code: "CRC",
    number: "188",
    digits: 2,
    currency: "Costa Rican Colon",
    countries: ["Costa Rica"],
  },
  {
    code: "CUC",
    number: "931",
    digits: 2,
    currency: "Peso Convertible",
    countries: ["Cuba"],
  },
  {
    code: "CUP",
    number: "192",
    digits: 2,
    currency: "Cuban Peso",
    countries: ["Cuba"],
  },
  {
    code: "CVE",
    number: "132",
    digits: 2,
    currency: "Cabo Verde Escudo",
    countries: ["Cabo Verde"],
  },
  {
    code: "CZK",
    number: "203",
    digits: 2,
    currency: "Czech Koruna",
    countries: ["Czechia"],
  },
  {
    code: "DJF",
    number: "262",
    digits: 0,
    currency: "Djibouti Franc",
    countries: ["Djibouti"],
  },
  {
    code: "DKK",
    number: "208",
    digits: 2,
    currency: "Danish Krone",
    countries: ["Denmark", "Faroe Islands (The)", "Greenland"],
  },
  {
    code: "DOP",
    number: "214",
    digits: 2,
    currency: "Dominican Peso",
    countries: ["Dominican Republic (The)"],
  },
  {
    code: "DZD",
    number: "012",
    digits: 2,
    currency: "Algerian Dinar",
    countries: ["Algeria"],
  },
  {
    code: "EGP",
    number: "818",
    digits: 2,
    currency: "Egyptian Pound",
    countries: ["Egypt"],
  },
  {
    code: "ERN",
    number: "232",
    digits: 2,
    currency: "Nakfa",
    countries: ["Eritrea"],
  },
  {
    code: "ETB",
    number: "230",
    digits: 2,
    currency: "Ethiopian Birr",
    countries: ["Ethiopia"],
  },
  {
    code: "EUR",
    number: "978",
    digits: 2,
    currency: "Euro",
    countries: [
      "Åland Islands",
      "Andorra",
      "Austria",
      "Belgium",
      "Cyprus",
      "Estonia",
      "European Union",
      "Finland",
      "France",
      "French Guiana",
      "French Southern Territories (The)",
      "Germany",
      "Greece",
      "Guadeloupe",
      "Holy See (The)",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Martinique",
      "Mayotte",
      "Monaco",
      "Montenegro",
      "Netherlands (The)",
      "Portugal",
      "Réunion",
      "Saint Barthélemy",
      "Saint Martin (French Part)",
      "Saint Pierre and Miquelon",
      "San Marino",
      "Slovakia",
      "Slovenia",
      "Spain",
    ],
  },
  {
    code: "FJD",
    number: "242",
    digits: 2,
    currency: "Fiji Dollar",
    countries: ["Fiji"],
  },
  {
    code: "FKP",
    number: "238",
    digits: 2,
    currency: "Falkland Islands Pound",
    countries: ["Falkland Islands (The) [Malvinas]"],
  },
  {
    code: "GBP",
    number: "826",
    digits: 2,
    currency: "Pound Sterling",
    countries: [
      "Guernsey",
      "Isle of Man",
      "Jersey",
      "United Kingdom of Great Britain and Northern Ireland (The)",
    ],
  },
  {
    code: "GEL",
    number: "981",
    digits: 2,
    currency: "Lari",
    countries: ["Georgia"],
  },
  {
    code: "GHS",
    number: "936",
    digits: 2,
    currency: "Ghana Cedi",
    countries: ["Ghana"],
  },
  {
    code: "GIP",
    number: "292",
    digits: 2,
    currency: "Gibraltar Pound",
    countries: ["Gibraltar"],
  },
  {
    code: "GMD",
    number: "270",
    digits: 2,
    currency: "Dalasi",
    countries: ["Gambia (The)"],
  },
  {
    code: "GNF",
    number: "324",
    digits: 0,
    currency: "Guinean Franc",
    countries: ["Guinea"],
  },
  {
    code: "GTQ",
    number: "320",
    digits: 2,
    currency: "Quetzal",
    countries: ["Guatemala"],
  },
  {
    code: "GYD",
    number: "328",
    digits: 2,
    currency: "Guyana Dollar",
    countries: ["Guyana"],
  },
  {
    code: "HKD",
    number: "344",
    digits: 2,
    currency: "Hong Kong Dollar",
    countries: ["Hong Kong"],
  },
  {
    code: "HNL",
    number: "340",
    digits: 2,
    currency: "Lempira",
    countries: ["Honduras"],
  },
  {
    code: "HRK",
    number: "191",
    digits: 2,
    currency: "Kuna",
    countries: ["Croatia"],
  },
  {
    code: "HTG",
    number: "332",
    digits: 2,
    currency: "Gourde",
    countries: ["Haiti"],
  },
  {
    code: "HUF",
    number: "348",
    digits: 2,
    currency: "Forint",
    countries: ["Hungary"],
  },
  {
    code: "IDR",
    number: "360",
    digits: 2,
    currency: "Rupiah",
    countries: ["Indonesia"],
  },
  {
    code: "ILS",
    number: "376",
    digits: 2,
    currency: "New Israeli Sheqel",
    countries: ["Israel"],
  },
  {
    code: "INR",
    number: "356",
    digits: 2,
    currency: "Indian Rupee",
    countries: ["Bhutan", "India"],
  },
  {
    code: "IQD",
    number: "368",
    digits: 3,
    currency: "Iraqi Dinar",
    countries: ["Iraq"],
  },
  {
    code: "IRR",
    number: "364",
    digits: 2,
    currency: "Iranian Rial",
    countries: ["Iran (Islamic Republic Of)"],
  },
  {
    code: "ISK",
    number: "352",
    digits: 0,
    currency: "Iceland Krona",
    countries: ["Iceland"],
  },
  {
    code: "JMD",
    number: "388",
    digits: 2,
    currency: "Jamaican Dollar",
    countries: ["Jamaica"],
  },
  {
    code: "JOD",
    number: "400",
    digits: 3,
    currency: "Jordanian Dinar",
    countries: ["Jordan"],
  },
  {
    code: "JPY",
    number: "392",
    digits: 0,
    currency: "Yen",
    countries: ["Japan"],
  },
  {
    code: "KES",
    number: "404",
    digits: 2,
    currency: "Kenyan Shilling",
    countries: ["Kenya"],
  },
  {
    code: "KGS",
    number: "417",
    digits: 2,
    currency: "Som",
    countries: ["Kyrgyzstan"],
  },
  {
    code: "KHR",
    number: "116",
    digits: 2,
    currency: "Riel",
    countries: ["Cambodia"],
  },
  {
    code: "KMF",
    number: "174",
    digits: 0,
    currency: "Comorian Franc ",
    countries: ["Comoros (The)"],
  },
  {
    code: "KPW",
    number: "408",
    digits: 2,
    currency: "North Korean Won",
    countries: ["Korea (The Democratic People’s Republic Of)"],
  },
  {
    code: "KRW",
    number: "410",
    digits: 0,
    currency: "Won",
    countries: ["Korea (The Republic Of)"],
  },
  {
    code: "KWD",
    number: "414",
    digits: 3,
    currency: "Kuwaiti Dinar",
    countries: ["Kuwait"],
  },
  {
    code: "KYD",
    number: "136",
    digits: 2,
    currency: "Cayman Islands Dollar",
    countries: ["Cayman Islands (The)"],
  },
  {
    code: "KZT",
    number: "398",
    digits: 2,
    currency: "Tenge",
    countries: ["Kazakhstan"],
  },
  {
    code: "LAK",
    number: "418",
    digits: 2,
    currency: "Lao Kip",
    countries: ["Lao People’s Democratic Republic (The)"],
  },
  {
    code: "LBP",
    number: "422",
    digits: 2,
    currency: "Lebanese Pound",
    countries: ["Lebanon"],
  },
  {
    code: "LKR",
    number: "144",
    digits: 2,
    currency: "Sri Lanka Rupee",
    countries: ["Sri Lanka"],
  },
  {
    code: "LRD",
    number: "430",
    digits: 2,
    currency: "Liberian Dollar",
    countries: ["Liberia"],
  },
  {
    code: "LSL",
    number: "426",
    digits: 2,
    currency: "Loti",
    countries: ["Lesotho"],
  },
  {
    code: "LYD",
    number: "434",
    digits: 3,
    currency: "Libyan Dinar",
    countries: ["Libya"],
  },
  {
    code: "MAD",
    number: "504",
    digits: 2,
    currency: "Moroccan Dirham",
    countries: ["Morocco", "Western Sahara"],
  },
  {
    code: "MDL",
    number: "498",
    digits: 2,
    currency: "Moldovan Leu",
    countries: ["Moldova (The Republic Of)"],
  },
  {
    code: "MGA",
    number: "969",
    digits: 2,
    currency: "Malagasy Ariary",
    countries: ["Madagascar"],
  },
  {
    code: "MKD",
    number: "807",
    digits: 2,
    currency: "Denar",
    countries: ["Macedonia (The Former Yugoslav Republic Of)"],
  },
  {
    code: "MMK",
    number: "104",
    digits: 2,
    currency: "Kyat",
    countries: ["Myanmar"],
  },
  {
    code: "MNT",
    number: "496",
    digits: 2,
    currency: "Tugrik",
    countries: ["Mongolia"],
  },
  {
    code: "MOP",
    number: "446",
    digits: 2,
    currency: "Pataca",
    countries: ["Macao"],
  },
  {
    code: "MRU",
    number: "929",
    digits: 2,
    currency: "Ouguiya",
    countries: ["Mauritania"],
  },
  {
    code: "MUR",
    number: "480",
    digits: 2,
    currency: "Mauritius Rupee",
    countries: ["Mauritius"],
  },
  {
    code: "MVR",
    number: "462",
    digits: 2,
    currency: "Rufiyaa",
    countries: ["Maldives"],
  },
  {
    code: "MWK",
    number: "454",
    digits: 2,
    currency: "Malawi Kwacha",
    countries: ["Malawi"],
  },
  {
    code: "MXN",
    number: "484",
    digits: 2,
    currency: "Mexican Peso",
    countries: ["Mexico"],
  },
  {
    code: "MXV",
    number: "979",
    digits: 2,
    currency: "Mexican Unidad de Inversion (UDI)",
    countries: ["Mexico"],
  },
  {
    code: "MYR",
    number: "458",
    digits: 2,
    currency: "Malaysian Ringgit",
    countries: ["Malaysia"],
  },
  {
    code: "MZN",
    number: "943",
    digits: 2,
    currency: "Mozambique Metical",
    countries: ["Mozambique"],
  },
  {
    code: "NAD",
    number: "516",
    digits: 2,
    currency: "Namibia Dollar",
    countries: ["Namibia"],
  },
  {
    code: "NGN",
    number: "566",
    digits: 2,
    currency: "Naira",
    countries: ["Nigeria"],
  },
  {
    code: "NIO",
    number: "558",
    digits: 2,
    currency: "Cordoba Oro",
    countries: ["Nicaragua"],
  },
  {
    code: "NOK",
    number: "578",
    digits: 2,
    currency: "Norwegian Krone",
    countries: ["Bouvet Island", "Norway", "Svalbard and Jan Mayen"],
  },
  {
    code: "NPR",
    number: "524",
    digits: 2,
    currency: "Nepalese Rupee",
    countries: ["Nepal"],
  },
  {
    code: "NZD",
    number: "554",
    digits: 2,
    currency: "New Zealand Dollar",
    countries: [
      "Cook Islands (The)",
      "New Zealand",
      "Niue",
      "Pitcairn",
      "Tokelau",
    ],
  },
  {
    code: "OMR",
    number: "512",
    digits: 3,
    currency: "Rial Omani",
    countries: ["Oman"],
  },
  {
    code: "PAB",
    number: "590",
    digits: 2,
    currency: "Balboa",
    countries: ["Panama"],
  },
  {
    code: "PEN",
    number: "604",
    digits: 2,
    currency: "Sol",
    countries: ["Peru"],
  },
  {
    code: "PGK",
    number: "598",
    digits: 2,
    currency: "Kina",
    countries: ["Papua New Guinea"],
  },
  {
    code: "PHP",
    number: "608",
    digits: 2,
    currency: "Philippine Peso",
    countries: ["Philippines (The)"],
  },
  {
    code: "PKR",
    number: "586",
    digits: 2,
    currency: "Pakistan Rupee",
    countries: ["Pakistan"],
  },
  {
    code: "PLN",
    number: "985",
    digits: 2,
    currency: "Zloty",
    countries: ["Poland"],
  },
  {
    code: "PYG",
    number: "600",
    digits: 0,
    currency: "Guarani",
    countries: ["Paraguay"],
  },
  {
    code: "QAR",
    number: "634",
    digits: 2,
    currency: "Qatari Rial",
    countries: ["Qatar"],
  },
  {
    code: "RON",
    number: "946",
    digits: 2,
    currency: "Romanian Leu",
    countries: ["Romania"],
  },
  {
    code: "RSD",
    number: "941",
    digits: 2,
    currency: "Serbian Dinar",
    countries: ["Serbia"],
  },
  {
    code: "RUB",
    number: "643",
    digits: 2,
    currency: "Russian Ruble",
    countries: ["Russian Federation (The)"],
  },
  {
    code: "RWF",
    number: "646",
    digits: 0,
    currency: "Rwanda Franc",
    countries: ["Rwanda"],
  },
  {
    code: "SAR",
    number: "682",
    digits: 2,
    currency: "Saudi Riyal",
    countries: ["Saudi Arabia"],
  },
  {
    code: "SBD",
    number: "090",
    digits: 2,
    currency: "Solomon Islands Dollar",
    countries: ["Solomon Islands"],
  },
  {
    code: "SCR",
    number: "690",
    digits: 2,
    currency: "Seychelles Rupee",
    countries: ["Seychelles"],
  },
  {
    code: "SDG",
    number: "938",
    digits: 2,
    currency: "Sudanese Pound",
    countries: ["Sudan (The)"],
  },
  {
    code: "SEK",
    number: "752",
    digits: 2,
    currency: "Swedish Krona",
    countries: ["Sweden"],
  },
  {
    code: "SGD",
    number: "702",
    digits: 2,
    currency: "Singapore Dollar",
    countries: ["Singapore"],
  },
  {
    code: "SHP",
    number: "654",
    digits: 2,
    currency: "Saint Helena Pound",
    countries: ["Saint Helena, Ascension and Tristan Da Cunha"],
  },
  {
    code: "SLL",
    number: "694",
    digits: 2,
    currency: "Leone",
    countries: ["Sierra Leone"],
  },
  {
    code: "SOS",
    number: "706",
    digits: 2,
    currency: "Somali Shilling",
    countries: ["Somalia"],
  },
  {
    code: "SRD",
    number: "968",
    digits: 2,
    currency: "Surinam Dollar",
    countries: ["Suriname"],
  },
  {
    code: "SSP",
    number: "728",
    digits: 2,
    currency: "South Sudanese Pound",
    countries: ["South Sudan"],
  },
  {
    code: "STN",
    number: "930",
    digits: 2,
    currency: "Dobra",
    countries: ["Sao Tome and Principe"],
  },
  {
    code: "SVC",
    number: "222",
    digits: 2,
    currency: "El Salvador Colon",
    countries: ["El Salvador"],
  },
  {
    code: "SYP",
    number: "760",
    digits: 2,
    currency: "Syrian Pound",
    countries: ["Syrian Arab Republic"],
  },
  {
    code: "SZL",
    number: "748",
    digits: 2,
    currency: "Lilangeni",
    countries: ["Eswatini"],
  },
  {
    code: "THB",
    number: "764",
    digits: 2,
    currency: "Baht",
    countries: ["Thailand"],
  },
  {
    code: "TJS",
    number: "972",
    digits: 2,
    currency: "Somoni",
    countries: ["Tajikistan"],
  },
  {
    code: "TMT",
    number: "934",
    digits: 2,
    currency: "Turkmenistan New Manat",
    countries: ["Turkmenistan"],
  },
  {
    code: "TND",
    number: "788",
    digits: 3,
    currency: "Tunisian Dinar",
    countries: ["Tunisia"],
  },
  {
    code: "TOP",
    number: "776",
    digits: 2,
    currency: "Pa’anga",
    countries: ["Tonga"],
  },
  {
    code: "TRY",
    number: "949",
    digits: 2,
    currency: "Turkish Lira",
    countries: ["Turkey"],
  },
  {
    code: "TTD",
    number: "780",
    digits: 2,
    currency: "Trinidad and Tobago Dollar",
    countries: ["Trinidad and Tobago"],
  },
  {
    code: "TWD",
    number: "901",
    digits: 2,
    currency: "New Taiwan Dollar",
    countries: ["Taiwan (Province of China)"],
  },
  {
    code: "TZS",
    number: "834",
    digits: 2,
    currency: "Tanzanian Shilling",
    countries: ["Tanzania, United Republic Of"],
  },
  {
    code: "UAH",
    number: "980",
    digits: 2,
    currency: "Hryvnia",
    countries: ["Ukraine"],
  },
  {
    code: "UGX",
    number: "800",
    digits: 0,
    currency: "Uganda Shilling",
    countries: ["Uganda"],
  },
  {
    code: "USD",
    number: "840",
    digits: 2,
    currency: "US Dollar",
    countries: [
      "American Samoa",
      "Bonaire, Sint Eustatius and Saba",
      "British Indian Ocean Territory (The)",
      "Ecuador",
      "El Salvador",
      "Guam",
      "Haiti",
      "Marshall Islands (The)",
      "Micronesia (Federated States Of)",
      "Northern Mariana Islands (The)",
      "Palau",
      "Panama",
      "Puerto Rico",
      "Timor-Leste",
      "Turks and Caicos Islands (The)",
      "United States Minor Outlying Islands (The)",
      "United States of America (The)",
      "Virgin Islands (British)",
      "Virgin Islands (U.S.)",
    ],
  },
  {
    code: "USN",
    number: "997",
    digits: 2,
    currency: "US Dollar (Next day)",
    countries: ["United States of America (The)"],
  },
  {
    code: "UYI",
    number: "940",
    digits: 0,
    currency: "Uruguay Peso en Unidades Indexadas (UI)",
    countries: ["Uruguay"],
  },
  {
    code: "UYU",
    number: "858",
    digits: 2,
    currency: "Peso Uruguayo",
    countries: ["Uruguay"],
  },
  {
    code: "UYW",
    number: "927",
    digits: 4,
    currency: "Unidad Previsional",
    countries: ["Uruguay"],
  },
  {
    code: "UZS",
    number: "860",
    digits: 2,
    currency: "Uzbekistan Sum",
    countries: ["Uzbekistan"],
  },
  {
    code: "VES",
    number: "928",
    digits: 2,
    currency: "Bolívar Soberano",
    countries: ["Venezuela (Bolivarian Republic Of)"],
  },
  {
    code: "VND",
    number: "704",
    digits: 0,
    currency: "Dong",
    countries: ["Viet Nam"],
  },
  {
    code: "VUV",
    number: "548",
    digits: 0,
    currency: "Vatu",
    countries: ["Vanuatu"],
  },
  {
    code: "WST",
    number: "882",
    digits: 2,
    currency: "Tala",
    countries: ["Samoa"],
  },
  {
    code: "XAF",
    number: "950",
    digits: 0,
    currency: "CFA Franc BEAC",
    countries: [
      "Cameroon",
      "Central African Republic (The)",
      "Chad",
      "Congo (The)",
      "Equatorial Guinea",
      "Gabon",
    ],
  },
  {
    code: "XAG",
    number: "961",
    digits: 0,
    currency: "Silver",
    countries: ["Zz11_silver"],
  },
  {
    code: "XAU",
    number: "959",
    digits: 0,
    currency: "Gold",
    countries: ["Zz08_gold"],
  },
  {
    code: "XBA",
    number: "955",
    digits: 0,
    currency: "Bond Markets Unit European Composite Unit (EURCO)",
    countries: ["Zz01_bond Markets Unit European_eurco"],
  },
  {
    code: "XBB",
    number: "956",
    digits: 0,
    currency: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    countries: ["Zz02_bond Markets Unit European_emu-6"],
  },
  {
    code: "XBC",
    number: "957",
    digits: 0,
    currency: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    countries: ["Zz03_bond Markets Unit European_eua-9"],
  },
  {
    code: "XBD",
    number: "958",
    digits: 0,
    currency: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    countries: ["Zz04_bond Markets Unit European_eua-17"],
  },
  {
    code: "XCD",
    number: "951",
    digits: 2,
    currency: "East Caribbean Dollar",
    countries: [
      "Anguilla",
      "Antigua and Barbuda",
      "Dominica",
      "Grenada",
      "Montserrat",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
    ],
  },
  {
    code: "XDR",
    number: "960",
    digits: 0,
    currency: "SDR (Special Drawing Right)",
    countries: ["International Monetary Fund (Imf) "],
  },
  {
    code: "XOF",
    number: "952",
    digits: 0,
    currency: "CFA Franc BCEAO",
    countries: [
      "Benin",
      "Burkina Faso",
      "Côte d'Ivoire",
      "Guinea-Bissau",
      "Mali",
      "Niger (The)",
      "Senegal",
      "Togo",
    ],
  },
  {
    code: "XPD",
    number: "964",
    digits: 0,
    currency: "Palladium",
    countries: ["Zz09_palladium"],
  },
  {
    code: "XPF",
    number: "953",
    digits: 0,
    currency: "CFP Franc",
    countries: ["French Polynesia", "New Caledonia", "Wallis and Futuna"],
  },
  {
    code: "XPT",
    number: "962",
    digits: 0,
    currency: "Platinum",
    countries: ["Zz10_platinum"],
  },
  {
    code: "XSU",
    number: "994",
    digits: 0,
    currency: "Sucre",
    countries: ['Sistema Unitario De Compensacion Regional De Pagos "Sucre"'],
  },
  {
    code: "XTS",
    number: "963",
    digits: 0,
    currency: "Codes specifically reserved for testing purposes",
    countries: ["Zz06_testing_code"],
  },
  {
    code: "XUA",
    number: "965",
    digits: 0,
    currency: "ADB Unit of Account",
    countries: ["Member Countries of the African Development Bank Group"],
  },
  {
    code: "XXX",
    number: "999",
    digits: 0,
    currency:
      "The codes assigned for transactions where no currency is involved",
    countries: ["Zz07_no_currency"],
  },
  {
    code: "YER",
    number: "886",
    digits: 2,
    currency: "Yemeni Rial",
    countries: ["Yemen"],
  },
  {
    code: "ZAR",
    number: "710",
    digits: 2,
    currency: "Rand",
    countries: ["Lesotho", "Namibia", "South Africa"],
  },
  {
    code: "ZMW",
    number: "967",
    digits: 2,
    currency: "Zambian Kwacha",
    countries: ["Zambia"],
  },
  {
    code: "ZWL",
    number: "932",
    digits: 2,
    currency: "Zimbabwe Dollar",
    countries: ["Zimbabwe"],
  },
];
export const curname = {
  0: "UAE Dirham",
  1: "Afghani",
  2: "Lek",
  3: "Armenian Dram",
  4: "Netherlands Antillean Guilder",
  5: "Kwanza",
  6: "Argentine Peso",
  7: "Australian Dollar",
  8: "Aruban Florin",
  9: "Azerbaijan Manat",
  10: "Convertible Mark",
  11: "Barbados Dollar",
  12: "Taka",
  13: "Bulgarian Lev",
  14: "Bahraini Dinar",
  15: "Burundi Franc",
  16: "Bermudian Dollar",
  17: "Brunei Dollar",
  18: "Boliviano",
  20: "Brazilian Real",
  21: "Bahamian Dollar",
  22: "Ngultrum",
  23: "Pula",
  24: "Belarusian Ruble",
  25: "Belize Dollar",
  26: "Canadian Dollar",
  27: "Congolese Franc",
  29: "Swiss Franc",
  31: "Unidad de Fomento",
  32: "Chilean Peso",
  33: "Yuan Renminbi",
  34: "Colombian Peso",
  36: "Costa Rican Colon",
  37: "Peso Convertible",
  38: "Cuban Peso",
  39: "Cabo Verde Escudo",
  40: "Czech Koruna",
  41: "Djibouti Franc",
  42: "Danish Krone",
  43: "Dominican Peso",
  44: "Algerian Dinar",
  45: "Egyptian Pound",
  46: "Nakfa",
  47: "Ethiopian Birr",
  48: "Euro",
  49: "Fiji Dollar",
  50: "Falkland Islands Pound",
  51: "Pound Sterling",
  52: "Lari",
  53: "Ghana Cedi",
  54: "Gibraltar Pound",
  55: "Dalasi",
  56: "Guinean Franc",
  57: "Quetzal",
  58: "Guyana Dollar",
  59: "Hong Kong Dollar",
  60: "Lempira",
  61: "Kuna",
  62: "Gourde",
  63: "Forint",
  64: "Rupiah",
  65: "New Israeli Sheqel",
  66: "Indian Rupee",
  67: "Iraqi Dinar",
  68: "Iranian Rial",
  69: "Iceland Krona",
  70: "Jamaican Dollar",
  71: "Jordanian Dinar",
  72: "Yen",
  73: "Kenyan Shilling",
  74: "Som",
  75: "Riel",
  76: "Comorian Franc ",
  77: "North Korean Won",
  78: "Won",
  79: "Kuwaiti Dinar",
  80: "Cayman Islands Dollar",
  81: "Tenge",
  82: "Lao Kip",
  83: "Lebanese Pound",
  84: "Sri Lanka Rupee",
  85: "Liberian Dollar",
  86: "Loti",
  87: "Libyan Dinar",
  88: "Moroccan Dirham",
  89: "Moldovan Leu",
  90: "Malagasy Ariary",
  91: "Denar",
  92: "Kyat",
  93: "Tugrik",
  94: "Pataca",
  96: "Mauritius Rupee",
  97: "Rufiyaa",
  98: "Malawi Kwacha",
  99: "Mexican Peso",
  101: "Malaysian Ringgit",
  102: "Mozambique Metical",
  103: "Namibia Dollar",
  104: "Naira",
  105: "Cordoba Oro",
  106: "Norwegian Krone",
  107: "Nepalese Rupee",
  108: "New Zealand Dollar",
  109: "Rial Omani",
  110: "Balboa",
  111: "Sol",
  112: "Kina",
  113: "Philippine Peso",
  114: "Pakistan Rupee",
  115: "Zloty",
  116: "Guarani",
  117: "Qatari Rial",
  118: "Romanian Leu",
  119: "Serbian Dinar",
  120: "Russian Ruble",
  121: "Rwanda Franc",
  122: "Saudi Riyal",
  123: "Solomon Islands Dollar",
  124: "Seychelles Rupee",
  125: "Sudanese Pound",
  126: "Swedish Krona",
  127: "Singapore Dollar",
  128: "Saint Helena Pound",
  129: "Leone",
  130: "Somali Shilling",
  131: "Surinam Dollar",
  134: "El Salvador Colon",
  135: "Syrian Pound",
  136: "Lilangeni",
  137: "Baht",
  138: "Somoni",
  139: "Turkmenistan New Manat",
  140: "Tunisian Dinar",
  141: "Pa’anga",
  142: "Turkish Lira",
  143: "Trinidad and Tobago Dollar",
  144: "New Taiwan Dollar",
  145: "Tanzanian Shilling",
  146: "Hryvnia",
  147: "Uganda Shilling",
  148: "US Dollar",
  151: "Peso Uruguayo",
  153: "Uzbekistan Sum",
  155: "Dong",
  156: "Vatu",
  157: "Tala",
  158: "CFA Franc BEAC",
  159: "Silver",
  160: "Gold",
  165: "East Caribbean Dollar",
  166: "SDR (Special Drawing Right)",
  167: "CFA Franc BCEAO",
  169: "CFP Franc",
  175: "Yemeni Rial",
  176: "Rand",
  177: "Zambian Kwacha",
  178: "Zimbabwe Dollar",
};
